# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "site"
destination:    ./_gh_pages
host:           "localhost"
port:           9001
baseurl:        ""
url:            "https://bootstrap.rtlcss.com"
encoding:       UTF-8
exclude:
  - docs/4.2/assets/scss/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              Bootstrap 4 RTL
description:        "The most popular HTML, CSS, and JS library in the world made right-to-left."
twitter:            rtlcss
authors:            "Mark Otto, Jacob Thornton, and Bootstrap contributors"
social_image_path:  /docs/4.2/assets/brand/bootstrap-social.png
social_logo_path:   /docs/4.2/assets/brand/bootstrap-social-logo.png

# Custom variables
current_version:      4.2.1
current_ruby_version: 4.2.1
docs_version:         4.2
repo:                 "https://github.com/RTLCSS/bootstrap"
slack:                "https://bootstrap-slack.herokuapp.com"
blog:                 "https://blog.getbootstrap.com"
expo:                 "https://expo.getbootstrap.com"
themes:               "https://themes.getbootstrap.com"

download:
  source:           "https://github.com/RTLCSS/bootstrap/archive/v4.2.1-rtl.zip"
  dist:             "https://github.com/RTLCSS/bootstrap/releases/download/v4.2.1/bootstrap-4.2.1-rtl-dist.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  rtlcss:           "https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css"
  rtlcss_hash:      "sha384-vus3nQHTD+5mpDiZ4rkEPlnkcyTP+49BhJ4wJeJunw06ZAp+wzzeBPUXr42fi8If"
  css:              "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
  css_hash:         "sha384-CKHFSO+alj8INnPTr6aTHcZfWxiUMck+E/gmzluv3nw0QiPeBS2hRjV8ImTZS5Yd"
  js:               "https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"
  js_hash:          "sha384-a9xOd0rz8w0J8zqj1qJic7GPFfyMfoiuDjC9rqXlVOcGO/dmRqzMn34gZYDTel8k"
  js_bundle:        "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js"
  js_bundle_hash:   "sha384-K/wjzuoV8a4rD2q1L2clnXIYLNmQiFganXCXSzSWUpFGF04s38f9vwnQFj2NUhDy"
  jquery:           "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash:      "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
  popper_hash:      "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"
